# Generated by Django 5.2.4 on 2025-07-31 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_ticket'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
