# Generated by Django 5.2.4 on 2025-09-20 15:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0008_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fowlowing',
            field=models.ManyToManyField(related_name='followers', through='social.Contact', to=settings.AUTH_USER_MODEL),
        ),
    ]
